{{- if.Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-auth-s3-nginx.fullname" . }}-secret-env
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .name }}: {{ .value }}
  {{- end }}
{{- end }}

{{- if .Values.secretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-auth-s3-nginx.fullname" . }}-secret-files
type: Opaque
data:
  {{- range .Values.secretFile }}
  {{ .name }}: {{ .data }}
  {{- end }}
{{- end }}
